weblab2/Models/ErrorViewModel.cs
using System;

namespace weblab2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

weblab2/Models/ResultModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace weblab2.Models
{
    public class ResultModel
    {
        public int first { get; set; }
        public int second { get; set; }
        public int calculationResult { get; set; }
        public string operation { get; set; }

        public ResultModel() { }
        public ResultModel(int first,int second,string operation)
        {
            this.first = first;
            this.second = second;
            this.operation = operation;
        }
    }
}

weblab2/Controllers/FormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using weblab2.Models;

namespace weblab2.Controllers
{
    public class FormController : Controller
    {
        private int calculate(int first, int second, string operation)
        {
            switch (operation)
            {
                case "+":
                    return first + second;
                case "-":
                    return first - second;
                case "*":
                    return first * second;

                case "/":
                    if (second == 0)
                    {
                        return 0;
                    }
                    return first / second;
                default:
                    return 0;
            }
        }

        public IActionResult ManualSingle(int first, string operation, int second)
        {
            if (Request.Method == "GET")
            {
                ViewBag.h1 = "ManualSingle";
                return View("MainForm");
            }
            if (Request.Method == "POST")
            {
                int result = this.calculate(first, second, operation);
                ViewBag.result = $"{result}";
                return View("ResultForm");
            }
            return View("Index");
        }
        [HttpGet]
        public IActionResult ManualSep()
        {
            ViewBag.h1 = "ManualSep";
            return View("MainForm");
        }
        [HttpPost]
        public IActionResult ManualSep(int first, string operation, int second)
        {
            int result = this.calculate(first, second, operation);
            ViewBag.result = $"{result}";
            return View("ResultForm");
        }

        [HttpGet]
        public IActionResult ModelBindPar()
        {
            ResultModel rm = new ResultModel();
            ViewBag.h1 = "ModelBindPar";
            return View("MainFormModel", rm);
        }

        [HttpPost]
        public IActionResult ModelBindPar(int first, int second, string operation)
        {
            ResultModel rm = new ResultModel(first, second, operation);
            rm.calculationResult = this.calculate(rm.first, rm.second, rm.operation);
            return View("ResultFormModel", rm);
        }
        [HttpGet]
        public IActionResult ModelBindSep()
        {
            ResultModel rm = new ResultModel();
            ViewBag.h1 = "ModelBindSep";
            return View("MainFormModel", rm);
        }

        [HttpPost]
        public IActionResult ModelBindSep(ResultModel rm)
        {
            //ResultModel rm = new ResultModel(first, second, operation);
            rm.calculationResult = this.calculate(rm.first, rm.second, rm.operation);
            return View("ResultFormModel", rm);
        }
    }
}

weblab2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using weblab2.Models;

namespace weblab2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

weblab2/Views/Form/MainForm.cshtml
@{
    ViewData["Title"] = "Index";
}
<h1>@ViewBag.h1</h1>
<form method="post">
    <div>
        <div><field name="first" /></div>
        <div><selector name="operation"></selector></div>
        <div><field name="second" /></div>
    </div>
    <input type="submit" value="Result" />
</form>

weblab2/Views/Form/MainFormModel.cshtml
@{
    ViewData["Title"] = "Index";
}
@model weblab2.Models.ResultModel
<h1>@ViewBag.h1</h1>
<form  asp-action="ModelBindSep" asp-controller="Form" method="post">
    <div>
        <div><field name="first" value="@Model.first" /></div>
        <div><selector name="operation" default="@Model.operation"></selector></div>
        <div><field name="second" value="@Model.second" /></div>
    </div>
    <input type="submit" value="Result" />
</form>

weblab2/Views/Form/ResultForm.cshtml
@{
    ViewData["Title"] = "ResultForm";
}
<h1>ResultForm</h1>
<div>
    @ViewBag.result
</div>

weblab2/Views/Form/ResultFormModel.cshtml
@{
    ViewData["Title"] = "ResultFormModel";
}
@model weblab2.Models.ResultModel
<h1>ResultFormModel</h1>
<div>
    @Model.calculationResult
</div>

weblab2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Calc Service";
    ViewData["h3"] = "Form parameters parsing demo";
}
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <ul>
        <li><a href="/form/ManualSingle">Manual parsing in single action</a></li>
        <li><a href="/form/ManualSep">Manual parsing in separate actions</a></li>
        <li><a href="/form/ModelBindPar">Model binding (parameters)</li>
        <li><a href="/form/ModelBindSep">Modelbind sep (separate model)</a></li>
    </ul>
</body>
</html>

weblab2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</head>
<body>
    <!--меню-->
    <nav class="navbar navbar-expand-md bg-dark">
        <div class="container">
            <div>
                <ul class="nav navbar-nav">
                    <li><a href="~/Home/Index" class="navbar-brand">Главная</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!--основной контент-->
    <div class="container body-content">
        <br>
        <h3>@ViewData["h3"]</h3>
        @RenderBody()
        <hr />
        
    </div>
</body>
</html>